-- Image generated by dbdiagram.io

table Account [headercolor: #2D6512] {
  id int [pk]
  first_name StringField
  last_name StringField
  email StringField
  avatar ImageField
  phone_number StringField
  current_subscription ForeignKey
}

table Studio [headercolor: #4B82B0] {
  id int [pk]
  name StringField
  address StringField
  latitude FloatField
  longitude FloatField
  postal_code StringField
  phone_number StringField
  // images
}

table StudioImage [headercolor: #4B82B0] {
  studio ForeignKey
  image ImageField
}
Ref: StudioImage.studio > Studio.id

table Amenities [headercolor: #4B82B0] {
  studio ForeignKey
  type StringField
  quantity int
}
Ref: Amenities.studio > Studio.id

table Class [headercolor: #EB801B] {
  id int [pk]
  studio ForeignKey
  name StringField
  description TextField
  coach StringField
  // keywords type could change...
  // assess during implementation
  duration DurationField
}
Ref: Class.studio > Studio.id

table Keywords [headercolor: #EB801B] {
  keyword StringField
  class ForeignKey
}
Ref: Keywords.class > Class.id

// Use this table if you want to cancel 
// one time in a recursive class
table ClassTimeTable [headercolor: #EB801B] {
  id int [pk]
  class ForeignKey
  time DateTimeField
  spotleft IntegerField
}
Ref: ClassTimeTable.class > Class.id

table SubscriptionPlan [headercolor: #79AD51] {
  id int [pk]
  payment DecimalField
  // one of "monthly", "yearly", etc
  // change if more complexity needed
  interval StringField
}

table CurrentSubscription [headercolor: #126E7A] {
  id int [pk]
  plan ForeignKey
  expiration DateTimeField
}
Ref: CurrentSubscription.plan - SubscriptionPlan.id

table PaymentInfo [headercolor: #24BAB1] {
  account ForeignKey
  card_number IntegerField
  card_expiry IntegerField
}
Ref: PaymentInfo.account - Account.id
Ref: Account.current_subscription - CurrentSubscription.id

table PaymentHistory [headercolor: #24BAB1] {
  id int [pk]
  account ForeignKey
  timestamp DateTimeField
  amount DecimalField
  card_number IntegerField
  card_expiry IntegerField
}
Ref: PaymentHistory.account > Account.id

table EnrollClass [headercolor: #DE65C3] {
  account ForeignKey
  classtime ForeignKey
}
Ref: EnrollClass.account > Account.id
Ref: EnrollClass.classtime > ClassTimeTable.id