# Generated by Django 4.1.3 on 2022-11-12 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=250)),
                ('duration', models.DurationField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfc_class', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=250)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('spotleft', models.IntegerField()),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='classes.class')),
            ],
        ),
    ]
