# Generated by Django 4.1.3 on 2022-11-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("coach", models.CharField(max_length=250)),
                ("keywords", models.TextField()),
                ("capacity", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfc_class",
                        to="studios.studio",
                    ),
                ),
            ],
        ),
    ]
