# Generated by Django 4.1.3 on 2022-11-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscriptionplan_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currentsubscription",
            name="studio",
        ),
    ]
