# Generated by Django 4.1.3 on 2022-11-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_avatar"),
        ("subscriptions", "0003_remove_currentsubscription_studio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentsubscription",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_subscription",
                to="accounts.account",
                unique=True,
            ),
        ),
    ]
