# Generated by Django 4.1.3 on 2022-11-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0002_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studioimage",
            name="image",
            field=models.ImageField(
                upload_to="studios/<django.db.models.fields.related.ForeignKey>/"
            ),
        ),
    ]
