# Generated by Django 4.1.3 on 2022-11-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0003_alter_studioimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studioimage",
            name="image",
            field=models.ImageField(upload_to="studios/"),
        ),
    ]
