# Generated by Django 4.1.3 on 2022-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0004_alter_studioimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="phone_number",
            field=models.CharField(max_length=250),
        ),
    ]
