# Generated by Django 4.1.3 on 2022-11-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0005_alter_studio_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenities",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
